# Generated by Django 6.0.3 on 2026-03-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_moderated_at_listing_moderated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='sale_mode',
            field=models.CharField(blank=True, choices=[('sell', 'Sell'), ('rent', 'Rent'), ('ads', 'Ads')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
    ]
