# Generated by Django 6.0.3 on 2026-03-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_listing_sale_mode_alter_listing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='upi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('business_ad', 'Business Ad'), ('house', 'House'), ('parcel', 'Parcel'), ('car', 'Car')], max_length=20),
        ),
    ]
