# Generated by Django 6.0.3 on 2026-03-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_upi_alter_listing_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='has_electricity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_water',
            field=models.BooleanField(default=False),
        ),
    ]
