# Generated by Django 6.0.3 on 2026-03-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_latitude_alter_listing_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=50, null=True),
        ),
    ]
