# Generated by Django 6.0.3 on 2026-03-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='car_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='car_condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='car_fuel_type',
            field=models.CharField(blank=True, choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='car_make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='car_mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='car_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='car_transmission',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='car_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
