# Generated by Django 6.0.3 on 2026-03-22 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_listing_car_color_listing_car_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='visibility_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
