# Generated by Django 6.0.3 on 2026-03-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='negotiable',
            field=models.BooleanField(default=False),
        ),
    ]
