# Generated by Django 6.0.3 on 2026-03-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_listingcontactevent_listingviewevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='call_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='whatsapp_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
