# Generated by Django 6.0.3 on 2026-03-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_listing_call_clicks_listing_whatsapp_clicks'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('gif', 'GIF')], default='video', max_length=10)),
                ('file', models.FileField(upload_to='promo_banners/')),
                ('target_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
