# Generated by Django 6.0.3 on 2026-03-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_promobanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='clothes_category',
            field=models.CharField(blank=True, help_text='Example: shirt, trouser, dress, shoes, jacket', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='clothes_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='clothes_gender',
            field=models.CharField(blank=True, choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex'), ('kids', 'Kids')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='clothes_material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='clothes_size',
            field=models.CharField(blank=True, choices=[('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL'), ('xxxl', 'XXXL')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='delivery_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Example: 120x60x75 cm', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='food_category',
            field=models.CharField(blank=True, help_text='Example: fresh food, cooked food, drink, snack, bakery', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='food_unit',
            field=models.CharField(blank=True, choices=[('piece', 'Piece'), ('kg', 'Kg'), ('gram', 'Gram'), ('liter', 'Liter'), ('ml', 'Ml'), ('pack', 'Pack'), ('plate', 'Plate'), ('box', 'Box'), ('bottle', 'Bottle')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='food_weight_volume',
            field=models.CharField(blank=True, help_text='Example: 1kg, 500ml, 12 pieces', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_home_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='home_product_category',
            field=models.CharField(blank=True, help_text='Example: cookware, furniture, decor, appliance, storage', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_perishable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_prepared_food',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='product_condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='warranty_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='weight',
            field=models.CharField(blank=True, help_text='Example: 5kg', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('business_ad', 'Business Ad'), ('house', 'House'), ('parcel', 'Parcel'), ('car', 'Car'), ('clothes_product', 'Clothes Product'), ('food_product', 'Food Product'), ('home_kitchen_product', 'Home & Kitchen Product')], max_length=30),
        ),
    ]
