# Generated by Django 6.0.3 on 2026-03-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_listing_brand_listing_clothes_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='stock_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
