# Generated by Django 6.0.3 on 2026-03-24 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_listingviewlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingviewlog',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='listings.listing'),
        ),
        migrations.AddIndex(
            model_name='listinginterest',
            index=models.Index(fields=['listing', 'user'], name='listings_li_listing_661b8f_idx'),
        ),
        migrations.AddIndex(
            model_name='listinginterest',
            index=models.Index(fields=['created_at'], name='listings_li_created_aaa0b9_idx'),
        ),
        migrations.AddIndex(
            model_name='listingviewlog',
            index=models.Index(fields=['listing', 'session_key', 'created_at'], name='listings_li_listing_4933e1_idx'),
        ),
        migrations.AddIndex(
            model_name='listingviewlog',
            index=models.Index(fields=['listing', 'ip_address', 'created_at'], name='listings_li_listing_a2ea1b_idx'),
        ),
        migrations.AddIndex(
            model_name='listingviewlog',
            index=models.Index(fields=['created_at'], name='listings_li_created_f1fc9d_idx'),
        ),
    ]
