# Generated by Django 6.0.3 on 2026-03-24 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_alter_listingviewlog_listing_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='listinginterest',
            name='listings_li_listing_661b8f_idx',
        ),
        migrations.RemoveIndex(
            model_name='listinginterest',
            name='listings_li_created_aaa0b9_idx',
        ),
        migrations.AlterUniqueTogether(
            name='listinginterest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='listinginterest',
            name='anonymous_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listinginterest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='listinginterest',
            constraint=models.UniqueConstraint(fields=('listing', 'user'), name='unique_listing_interest_user'),
        ),
        migrations.AddConstraint(
            model_name='listinginterest',
            constraint=models.UniqueConstraint(fields=('listing', 'anonymous_user_id'), name='unique_listing_interest_anonymous'),
        ),
    ]
