# Generated by Django 6.0.3 on 2026-03-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_visitorlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorlog',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='user_agent',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['visited_at'], name='moderation__visited_c97bf0_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['ip_address'], name='moderation__ip_addr_99052b_idx'),
        ),
        migrations.AddIndex(
            model_name='visitorlog',
            index=models.Index(fields=['session_key'], name='moderation__session_b6bcea_idx'),
        ),
    ]
